apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-vlan10-mgmt
  namespace: metallb-system
spec:
  addresses: ["172.26.10.150-172.26.10.199"]
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: adv-vlan10-mgmt
  namespace: metallb-system
spec:
  ipAddressPools: ["pool-vlan10-mgmt"]
  interfaces: ["vlan10"]
  