apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-vlan30-public
  namespace: metallb-system
spec:
  addresses: ["172.26.30.150-172.26.30.199"]
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: adv-vlan30-public
  namespace: metallb-system
spec:
  ipAddressPools: ["pool-vlan30-public"]
  interfaces: ["vlan30"]
  