apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-vlan100-admin
  namespace: metallb-system
spec:
  addresses: ["172.26.100.150-172.26.100.199"]
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: adv-vlan100-admin
  namespace: metallb-system
spec:
  ipAddressPools: ["pool-vlan100-admin"]
  interfaces: ["eth0"]
  