apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - configmap-main.yaml
  - configmap-ipmi-h12.yaml
  - configmap-ipmi-h11.yaml
  - configmap-snmp-edgerouter.yaml
  - configmap-snmp-brocade.yaml
  - secret.yaml