apiVersion: v1
kind: Secret
metadata:
    name: longhorn-b2-backup
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ENDPOINTS: ENC[AES256_GCM,data:M+WqebDXuIL6EOKrTMsGNkBqhJeoHdyovIE8EZw8PZDa,iv:te8AYK1ZHDcikU5S58dyEjRiou7yX4z7m0GbF6n4MhU=,tag:l5Tj71QBWax6Qp2lRXwwLA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:4gijcXZ3VVM3Iif70zo5YkPQWFJfSlRaWw==,iv:ruTPZu18DB8ePk6CLsWkyJHmL8VJgiUjxTfwEv2ghM4=,tag:z5E/p5mUc0PbDDtRan8fHQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PA9Y1V491iA2ZFVwJ1R4Wsr2+Dw3yX/2cqao9n1xzA==,iv:ZcA+AEm6ZFEnT4/MuHitStCJG2m+rfjZIKD+FDg9w3I=,tag:E0fl+Mf7bGyjNDy86UISPg==,type:str]
sops:
    age:
        - recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTHZyRjd0bnk4OGwvakpZ
            aitISkdaTGhBTUxyK1Bkb2FhYmN1L3NkTFJZCkcwQnIrUC9Wb0dDSmtEMW4yZ1Iz
            d29hWW5hZTMzVTQwc282ZGJQNm5rdTgKLS0tIGFUYzY3Y0NoenVBa2RLU3dwaWNX
            emxja1Zxek5FSWJiYWszSXF4bmtpQVUKv+ks4Zac4BzuYsVBWP0XBffgHZvxHsr7
            0LxPTSKvp9KKFcSHMUGSRmbcU1zVA6Wr9Y9Df+tpXh8gwu1UoYaqrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T16:36:06Z"
    mac: ENC[AES256_GCM,data:kpP1FUgc7M1wl9fXjm3mnpcAMvWqE7IdEEdIG0P4B6hl4a3s988W8mGtvf1KbCuChIaAMYfefRuX8A9RYv96RcLe5fDWqqaA1QeUh/nuH8KKF2pKxj3xxk+QzU+dsSSkoI9Hlav7Oln0WorY8SC1o9//aTvONuJBryDViGh3mqM=,iv:i/VdJPzMVYV6w+Cu8d2j45dfIzGVvY806pQ3Ai5z4JM=,tag:Xqk6rWx/cWe0rtRK65I1dg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
