apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Fq8NFFVTG84nJY1Xv9QnkQR/oAPR0lgpNok7vt2Uyu1SwfYuo19efQ==,iv:EXb+FZP3jaaZFOmqrzXxUJ/oQPLOMtDD1eNr6ji2gvA=,tag:vYCQvHJxHRw3YHEMi7er6w==,type:str]
sops:
    age:
        - recipient: age1fpu8x7ang8lv3vyjvswctpd609lgkzs4a5pudedua7h7gf8v63zs22wk39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS0lwSTlyQ3ZERGFFRXNy
            bU9vNGpaQzZxODZnMTZLZW0vUXdvRWpkQ0dVCktiSCtSbTdoQk1uRStFK0cwNVMv
            NjVURzROZnlIQnQ5VzI4Z0x4SFRyQ1UKLS0tIFh3QmVCckFMRUVWL20rRFY1NzZZ
            UC9CVm5YaS9kem5BT1lxTURNcEwrbFkKCc8s08/3Fywbq+u+gbnaLpuzMnoiUQp6
            SyFCCrbPL2FscusJFj30y0GJiR4MWybtw9AcWqQlO+HUcNQYCA4jsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T16:27:17Z"
    mac: ENC[AES256_GCM,data:7V8aPoYo+7XzhidQpHy+qb9FTraUPVLoMeYoN6oi4LB/Cb1nO/65MB0FtVeLUQGCxfV3q3qKcgbtrXHKsgJv8erYd61oP6oiPn6L38i7RzpJYFgrMev/94w4vz9WShFG/MsYNF0/95MqJOrxY5PiGNzg+otH0Yn0goUoZrJL+wY=,iv:JUz/o/xEwTb9hc7F8qH3hPbH0haCtu6OCmbroEoQaK8=,tag:J4XwBna3YdLbGJT5/zBZhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
