apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-admin-deny-nginx
  namespace: svc-vaultwarden
data:
  default.conf: |
    server {
      listen 8080;
      location / {
        return 403;
      }
    }
