apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden-admin-deny
  namespace: svc-vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden-admin-deny
  template:
    metadata:
      labels:
        app: vaultwarden-admin-deny
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cfg
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: cfg
          configMap:
            name: vaultwarden-admin-deny-nginx
